"""Added bloqueado Column

Revision ID: 2ce3e8d653b2
Revises: 7ff8de0b3e0d
Create Date: 2024-01-30 10:06:18.062043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce3e8d653b2'
down_revision: Union[str, None] = '7ff8de0b3e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('fatores_email', sa.Boolean(), nullable=True))
    op.drop_column('pessoas', 'fatores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('fatores', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('pessoas', 'fatores_email')
    # ### end Alembic commands ###
