"""Added bloqueado Column

Revision ID: 42b689c1ad94
Revises: 2ce3e8d653b2
Create Date: 2024-01-30 13:36:41.370746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b689c1ad94'
down_revision: Union[str, None] = '2ce3e8d653b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
