"""Added ClienteAdm model

Revision ID: 4628a649da8f
Revises: 
Create Date: 2024-01-24 16:35:53.234737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4628a649da8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('nascimento', sa.String(length=11), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('foto', sa.String(length=1000), nullable=True),
    sa.Column('adm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoas')
    # ### end Alembic commands ###
