"""Added bloqueado Column

Revision ID: 7ff8de0b3e0d
Revises: f7b77bc6023d
Create Date: 2024-01-29 16:14:38.333283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff8de0b3e0d'
down_revision: Union[str, None] = 'f7b77bc6023d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('telegram', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'telegram')
    # ### end Alembic commands ###
