"""Added bloqueado Column

Revision ID: b2841e58a6de
Revises: fe6966fc2eeb
Create Date: 2024-01-25 09:39:15.754700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2841e58a6de'
down_revision: Union[str, None] = 'fe6966fc2eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('bloqueado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'bloqueado')
    # ### end Alembic commands ###
