"""Added ClienteAdm model

Revision ID: f21eb2e52606
Revises: f44e06aec7a9
Create Date: 2024-01-24 17:41:54.095019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21eb2e52606'
down_revision: Union[str, None] = 'f44e06aec7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('data_criacao', sa.TIMESTAMP(), nullable=True))
    op.add_column('pessoas', sa.Column('data_atualizacao', sa.TIMESTAMP(), nullable=True))
    op.alter_column('pessoas', 'email', existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column('pessoas', 'senha', existing_type=sa.VARCHAR(length=500), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pessoas', 'senha', existing_type=sa.VARCHAR(length=500), nullable=False)
    op.alter_column('pessoas', 'email', existing_type=sa.VARCHAR(length=100), nullable=False)
    op.drop_column('pessoas', 'data_atualizacao')
    op.drop_column('pessoas', 'data_criacao')
    # ### end Alembic commands ###
