"""Added ClienteAdm model

Revision ID: f44e06aec7a9
Revises: 4628a649da8f
Create Date: 2024-01-24 17:03:36.887485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44e06aec7a9'
down_revision: Union[str, None] = '4628a649da8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('pessoas', sa.Column('senha', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'senha')
    op.drop_column('pessoas', 'email')
    # ### end Alembic commands ###
