"""Added bloqueado Column

Revision ID: f7b77bc6023d
Revises: b2841e58a6de
Create Date: 2024-01-29 11:27:15.450374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b77bc6023d'
down_revision: Union[str, None] = 'b2841e58a6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('fatores', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'fatores')
    # ### end Alembic commands ###
