"""Atualizando pessoas

Revision ID: fe6966fc2eeb
Revises: f21eb2e52606
Create Date: 2024-01-24 17:44:32.210641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6966fc2eeb'
down_revision: Union[str, None] = 'f21eb2e52606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
